### PR TITLE
Feat 241 multischeduletriggers 3.5

### PR DESCRIPTION
**Pull request by tlawrie**
Relates to boomerang-io/roadmap#241

Implements new WorkflowSchedules to allow Workflows to have multiple difference future run once and recurring schedule triggers.

_Note:_ this is the [prior PR](https://github.com/boomerang-io/flow.service.workflow/pull/124) based off of Release 3.5

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

### CODE REVIEW

**Comment by tlawrie** [comment]
**WorkflowSchedule**
```
{
    "workflowId": "61b834ab0057b3317394b947",
    "status": "active|inactive|deleted",
    "name":"",
    "description": "",
    "dateSchedule": "ISO Date",
    "cronSchedule": "CRON",
    "type": "runOnce|cron|advancedCron",
    "timezone": "Australia/Melbourne",
    "parameters": {
        "parameter1": ""
    },
    "labels": [{
        "key": "",
        "value": ""
    }]
}
```

**Notes**
- Timezone is only used for cron based schedules. runOnce uses an ISO date

**Questions**
1. Not sure if I should bother with the workflowId in the schedule payload when the URL has it as a path parameter?
2. Do we want a separate endpoint for a quick enable / disable of a schedule in addition to the PATCH?
The get  schedules/calendar which is meant to return all the dates for all the schedules in a workflow doesn't currently work. 3. Do we need it and what format would you like it back in? Possibly need to run you through it but you can see the List<Dates> thats returned with the individual schedule calendar.

**Endpoints**
GET /workflow/{workflowId}/schedules -> all the schedules for a workflow
GET /workflow/{workflowId}/schedules/calendar?startDate=ISO_DATE&endDate=ISO_DATE -> all the calendar entries for all the schedules in a workflow
POST /workflow/{workflowId}/schedule -> creates a schedule
GET /workflow/{workflowId}/schedule/{scheduleId} -> returns a particular schedule
GET /workflow/{workflowId}/schedule/{scheduleId}/calendar?startDate=ISO_DATE&endDate=ISO_DATE -> the calendar entries for a particular schedule in a workflow
PATCH /workflow/{workflowId}/schedule/{scheduleId} -> updates a particular schedule
DELETE /workflow/{workflowId}/schedule/{scheduleId} -> deletes a particular schedule

**Comment by tlawrie** [comment]
Design decision needed for what to do with scheduled workflows if the trigger is disabled / enabled.
- Provide a confirmation dialog that says, "this will disable all schedules and they will need to be individually enabled" [current implementation], OR
- make it so that the schedules have a mechanism to remember to be-renabled, i.e. use another status type of paused instead of inactive for ones that should be reenabled if the trigger is enabled. (we have to be able to tell the difference between the schedules that were disabled prior to the trigger being disabled so they aren't enabled if the trigger is)

**Comment by tlawrie** [comment]
Another question is what to do with schedules on export / import of a workflow? do we just provide a warning at export time saying that schedules are not exported with the workflow?

**Comment by tlawrie** [comment]
Updated endpoints based on integration with the UI. A majority have been moved to the higher level /schedules context rather than under a specific workflow.

**Schedules Endpoints**
GET /workflow/schedules?scopes=LIST<String>&workflowIds=LIST<String>&teamIds=LIST<String>&statuses=LIST<String>&types=LIST<String> -> all the schedules with a bunch of query parameters
GET /workflow/schedules/calendar?workflowId={id}&startDate=ISO_DATE&endDate=ISO_DATE -> all the calendar entries for all the schedules 
GET /workflow/schedules/validate/cron -> validates the cron expression. This is used by the current schedule trigger modal (but we will move to a different part of the UI)
POST /workflow/schedules/schedule -> creates a schedule
GET /workflow/schedules/{scheduleId} -> returns a particular schedule
GET /workflow/schedules/{scheduleId}/calendar?startDate=ISO_DATE&endDate=ISO_DATE -> the calendar entries for a particular schedule in a workflow
PATCH /workflow/schedules/{scheduleId} -> updates a particular schedule
DELETE /workflow/schedules/{scheduleId} -> deletes a particular schedule

**Workflow Specific Endpoints**
GET /workflow/workflow/{workflowId}/schedules -> all the schedules for a specific workflow
GET /workflow/workflow/{workflowId}/schedules/calendar -> all the calendar dates for all the schedules in a workflow

**Comment by tlawrie** [comment]
Hi @marcusdroy @amhudson this is now ready for review.

Outstanding items
- Run Scheduled Workflow (system task)
- Authorization on the schedules code

**Review by amhudson — APPROVED** [review]

**Review by marcusdroy — APPROVED** [review]

**Pull request merged**
