### PR TITLE
Integrate `SubHandler` interface into `EventingSubscriberClient`

### PR DESCRIPTION
**Pull request by corcoja**
This PR fixes an issues where `SubHandler` object ended up being cleared from memory by GC since it was assigned directly when subscribe method is invoked:

```java
tunnel.subscribe(new SubHandler() {
...
});
```

The `subscribe(SubHandler handler);` method keeps a weak reference to any handler to avoid circular references. To make sure that `SubHandler` stays in memory, it has been integrated into the `EventingSubscriberClient` class.

### CODE REVIEW

**Review by amhudson — APPROVED** [review]

**Comment by tlawrie** [comment]
Hi @corcoja @amhudson is there a GitHub Issue for this? and is it earmarked for 3.7.0 which closed last Friday?

**Comment by corcoja** [comment]
> Hi @corcoja @amhudson is there a GitHub Issue for this? and is it earmarked for 3.7.0 which closed last Friday?

Hi @tlawrie, I haven't opened a GitHub issue since this was a rather quick find and fix. When I created this PR the release `3.7.0` was still in progress and I decided to add this hotfix to it.

**Review by tlawrie — APPROVED** [review]

**Comment by tlawrie** [comment]
Hey @corcoja - not a problem. Approved. With the +2 squashed and merged as well.

**Comment by timrbula** [comment]
@tlawrie How best to verify this one?

**Comment by tlawrie** [comment]
That's an IBM question. Probably best to talk to @corcoja and @amhudson

**Comment by timrbula** [comment]
@corcoja @amhudson Any idea on this one? This is the one of the last remaining issues for this release.

**Comment by corcoja** [comment]
Hey @timrbula, this PR only changes how the Eventing handler is being persisted in the memory (weak vs strong). It doesn't change any business logic in the application itself.

> How best to verify this one?

I have tested this PR myself, so I would say we can move it to Done.

**Pull request merged**
