### PR TITLE
Feat 241 multischeduletriggers

### PR DESCRIPTION
**Pull request by corcoja**
This PR contains the upgraded eventing features that were merged into 3.4 (#126) but for some reason are not present in 3.5. I think it also includes (#132) but I'm not 100% sure since there are 2 unmerged branches for multi-schedule triggers:
image
image

### CODE REVIEW

**Comment by tlawrie** [comment]
Hi @corcoja the real schedules branch is `feat-241-multischeduletriggers-3.5` which is already merged into `release-3.5`

Does that mean we don't need this PR? I am confused. If a branch is missing from `release-3.5` can we not merge directly?

**Comment by corcoja** [comment]
> Does that mean we can instead merge `corcoja:feature/lib.eventing` into `release-3.5` or merge `release-3.4` into `release-3.5` to make sure it covers everything?

`lib.eventing` has been already merged into `release-3.4` (here #126), so I would go with merging `release-3.4` into `release-3.5`. I will open a new PR for this.

**Comment by corcoja** [comment]
There were some unpruned branches in my forked repo and this confused me. `release-3.4` has been already merged into `release-3.5` so it's all good. I have just double checked the code for `lib.eventing` and everything looks to be in place. Closing this PR.

**Comment by tlawrie** [comment]
Awesome. Thanks for checking @corcoja. I actually was worried about this happening.

**Pull request closed without merging**
